# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  configure:
    silent: true
    status:
      - test -d build
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

  configure-dev:
    silent: true
    status:
      - test -d build-dev
    cmds:
      - cmake -S . -B build-dev -DCMAKE_BUILD_TYPE=Debug -DCSTRUCT_DEV=ON

  build:
    silent: true
    cmds:
      - task: configure
      - cmake --build build

  build-dev:
    silent: true
    cmds:
      - task: configure-dev
      - cmake --build build-dev

  test:
    silent: true
    cmds:
      - task: build-dev
      - ctest --test-dir build-dev --output-on-failure

  clean:
    silent: true
    cmds:
      - rm -rf build-dev
      - rm -rf build
      - rm -rf Testing
